# Generated by Django 4.1.5 on 2023-01-20 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("mysite", "0002_rename_user_id_post_user")]

    operations = [
        migrations.RenameField(model_name="post", old_name="user", new_name="user_id")
    ]
