# Generated by Django 4.1.5 on 2023-01-20 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("mysite", "0003_rename_user_post_user_id")]

    operations = [
        migrations.RenameField(model_name="post", old_name="user_id", new_name="user")
    ]
