# Generated by Django 4.1.5 on 2023-01-20 23:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("mysite", "0006_post_likes_count")]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="comment",
            field=models.CharField(default="this comment is fake", max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="comment",
            name="post",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="mysite.post",
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="posted_at",
            field=models.DateTimeField(
                auto_now_add=True, default="2012-09-04 06:00:00+0800"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="comment",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="like",
            name="post",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="mysite.post",
                verbose_name="Post",
            ),
        ),
    ]
