# Generated by Django 4.1.5 on 2023-01-21 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0007_comment_comment_comment_post_comment_posted_at_and_more")
    ]

    operations = [
        migrations.AlterField(
            model_name="like",
            name="post",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="likes",
                to="mysite.post",
            ),
        )
    ]
