# Generated by Django 4.1.5 on 2023-01-21 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("mysite", "0008_alter_like_post")]

    operations = [
        migrations.AddField(
            model_name="like",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="likes",
                to=settings.AUTH_USER_MODEL,
            ),
        )
    ]
