name: CodersCamp
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v3
      - name: Build the Stack
        run: docker-compose -f docker-compose.yml build
      - name: Run DB Migrations
        run: docker-compose -f docker-compose.yml run --rm web python3 manage.py migrate
      - name: Run Django Tests
        run: docker-compose -f docker-compose.yml run --rm web python3 manage.py test
      - name: Tear down the Stack
        run: docker-compose -f docker-compose.yml down
        
        
  build_push_image_to_DockerHub:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 
    - name: Build the Docker image
      run: docker-compose -f docker-compose.yaml build 
    - name: tag Docker image
      run: docker tag shroukhegazi/coderscamp:$(date +%s)
    - name: Docker Push
      run: docker push shroukhegazi/coderscamp:$(date +%s)
